pipeline {
    agent any
    stages {
        stage('TMvalidation') {
            steps {
                build 'jenkinsjob1'
            }
        }
        stage('Test') {
            steps {
                echo 'its working' > test.txt
            }
        }
    }
}
