pipeline {
    agent any
    stages {
        stage('TM_validation') {
            steps {
                threatModeler()
            }
        }
        stage('Test') {
            steps {
                echo 'its working'
            }
        }
    }
}
