pipeline {
    agent any
    stages {
        stage('TM_validation') {
            steps {
                build 'jenkinsjob1'
            }
        }
        stage('Test') {
            steps {
                echo 'its working'
            }
        }
    }
}
